spring:
  datasource:
    username: root
    password: DQ971208
    url: jdbc:mysql://127.0.0.1:3306/learn?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 200
mybatis:
  type-aliases-package: com.kaiqiang.learn.distributed.lock.mysql
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl